# Generated by Django 3.2 on 2023-03-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesRPA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.CharField(choices=[('a', 'Link'), ('input', 'Input'), ('div', 'Div'), ('url', 'Goto')], max_length=50),
        ),
    ]
