# Generated by Django 3.2 on 2023-03-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesRPA', '0002_alter_element_element_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='xpath',
            field=models.TextField(blank=True, null=True),
        ),
    ]
