# Generated by Django 3.2 on 2023-03-07 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pagesRPA', '0003_page_xpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='element',
            name='mark',
            field=models.CharField(default=datetime.datetime(2023, 3, 7, 7, 4, 23, 765728, tzinfo=utc), max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default=datetime.datetime(2023, 3, 7, 7, 5, 4, 671068, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
