# Generated by Django 3.2 on 2023-03-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesRPA', '0004_auto_20230307_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
