# Generated by Django 3.2 on 2023-03-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesRPA', '0007_auto_20230307_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
