# Generated by Django 3.2 on 2023-03-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesRPA', '0009_auto_20230308_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='offset',
            field=models.IntegerField(default=0),
        ),
    ]
