# Generated by Django 3.2 on 2023-03-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesRPA', '0010_element_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.CharField(choices=[('a', 'Link'), ('input', 'Input'), ('div', 'Div'), ('button', 'Button'), ('dd', 'Dd'), ('url', 'Goto')], max_length=50),
        ),
    ]
