# Generated by Django 3.2 on 2023-03-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesRPA', '0011_alter_element_element_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='is_actived',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.CharField(choices=[('link', 'Link'), ('input', 'Input'), ('div', 'Div'), ('button', 'Button'), ('dd', 'Dd'), ('url', 'Goto')], max_length=50),
        ),
    ]
