# Generated by Django 3.2 on 2023-03-21 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesRPA', '0014_alter_element_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ('id',), 'permissions': [('duplicate_selected', 'Can copy element'), ('swap_sequence', 'Can swap element sequence')], 'verbose_name': 'Element', 'verbose_name_plural': 'Elements'},
        ),
    ]
